export default [
    {
        id: 1,
        name: 'Shashank Kumar',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },

    {
        id: 2,
        name: 'Piyush Singh',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },

    {
        id: 3,
        name: 'Sooraj Singh',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },

    {
        id: 4,
        name: 'Sharad Singh',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },

    {
        id: 4,
        name: 'Raveet Singh',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },

    {
        id: 6,
        name: 'Sweety Sahu',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },

    {
        id: 7,
        name: 'Simran Singh',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },

    {
        id: 8,
        name: 'Vaibhav Dixit',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },

    {
        id: 9,
        name: 'Prabhat Soni',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },
    
    {
        id: 10,
        name: 'Rishi',
        image: '',
        post: 'Operating Member',
        category: 'members',
        mail: '',
        fb_link: '',
        lnkdin_link: '',
    },
]